# Generated by Django 3.2.9 on 2021-12-02 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from_date', models.DateTimeField(auto_now_add=True)),
                ('borrowed_to_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(null=True)),
                ('book_isbn', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='manager.book')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issued_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('late_fees_charged', models.CharField(max_length=50)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('actual_return_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_was_returned', to='users.borrower')),
                ('book_isbn', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='manager.book')),
                ('borrowed_from_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_was_borrowed', to='users.borrower')),
                ('borrowed_to_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_to_return', to='users.borrower')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
