# Generated by Django 3.2.9 on 2021-12-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_payments_actual_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='borrowed_from_date',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='borrowed_to_date',
        ),
    ]
