# Generated by Django 3.2.9 on 2021-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211202_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
