# Generated by Django 3.2.9 on 2021-11-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211115_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_book_due',
            field=models.IntegerField(default=0),
        ),
    ]
