# Generated by Django 3.2.9 on 2021-11-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_isbn', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=1000)),
                ('book_image', models.CharField(max_length=550)),
                ('book_desc', models.TextField()),
                ('book_availability_status', models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Book availability', max_length=1, null=True)),
                ('book_total_copies', models.IntegerField(default=10)),
                ('book_available_copies', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_approval_status', models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', help_text='Book Request', max_length=1)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.genre'),
        ),
    ]
